export function meniny(pocetDni) {
  let meninyList = [
    '',
    'Alexandra, Karina',
    'Daniela',
    'Drahoslav',
    'Andrea',
    'Antónia',
    'Bohuslava',
    'Severín',
    'Alexej',
    'Dáša',
    'Malvína',
    'Ernest',
    'Rastislav',
    'Radovan',
    'Dobroslav',
    'Kristína',
    'Nataša',
    'Bohdana',
    'Drahomíra',
    'Dalibor',
    'Vincent',
    'Zora',
    'Miloš',
    'Timotej',
    'Gejza',
    'Tamara',
    'Bohuš',
    'Alfonz',
    'Gašpar',
    'Ema',
    'Emil',
    'Tatiana',
    'Erik, Erika',
    'Blažej',
    'Veronika',
    'Agáta',
    'Dorota',
    'Vanda',
    'Zoja',
    'Zdenko',
    'Gabriela',
    'Dezider',
    'Perla',
    'Arpád',
    'Valentín',
    'Pravoslav',
    'Ida, Liana',
    'Miloslava',
    'Jaromír',
    'Vlasta',
    'Lívia',
    'Eleonóra',
    'Etela',
    'Roman, Romana',
    'Matej',
    'Frederik, Frederika',
    'Viktor',
    'Alexander',
    'Zlatica',
    'Radomír',
    'Albín',
    'Anežka',
    'Bohumil',
    'Kazimír',
    'Fridrich',
    'Radoslav, Radoslava',
    'Tomáš',
    'Alan, Alana',
    'Františka',
    'Branislav, Bruno',
    'Angela, Angelika',
    'Gregor',
    'Vlastimil',
    'Matilda',
    'Svetlana',
    'Boleslav',
    'Ľubica',
    'Eduard',
    'Jozef',
    'Víťazoslav, Klaudius',
    'Blahoslav',
    'Beňadik',
    'Adrián',
    'Gabriel',
    'Marián',
    'Emanuel',
    'Alena',
    'Soňa',
    'Miroslav',
    'Vieroslava',
    'Benjamín',
    'Hugo',
    'Zita',
    'Richard',
    'Izidor',
    'Miroslava',
    'Irena',
    'Zoltán',
    'Albert',
    'Milena',
    'Igor',
    'Július',
    'Estera',
    'Aleš',
    'Justína',
    'Fedor',
    'Dana, Danica',
    'Rudolf, Rudolfa',
    'Valér',
    'Jela',
    'Marcel',
    'Ervín',
    'Slavomír',
    'Vojtech',
    'Juraj',
    'Marek',
    'Jaroslava',
    'Jaroslav',
    'Jarmila',
    'Lea',
    'Anastázia',
    '',
    'Žigmund',
    'Galina, Timea',
    'Florián',
    'Lesana, Lesia',
    'Hermína',
    'Monika',
    'Ingrida',
    'Roland',
    'Viktória',
    'Blažena',
    'Pankrác',
    'Servác',
    'Bonifác',
    'Žofia',
    'Svetozár',
    'Gizela, Aneta',
    'Viola',
    'Gertrúda',
    'Bernard',
    'Zina',
    'Júlia, Juliána',
    'Želmíra',
    'Ela',
    'Urban',
    'Dušan',
    'Iveta',
    'Viliam',
    'Vilma',
    'Ferdinand',
    'Petrana, Petronela',
    'Žaneta',
    'Oxana, Xénia',
    'Karolína',
    'Lenka',
    'Laura',
    'Norbert',
    'Róbert, Róberta',
    'Medard',
    'Stanislava',
    'Margaréta',
    'Dobroslava',
    'Zlatko',
    'Anton',
    'Vasil',
    'Vít',
    'Bianka, Blanka',
    'Adolf',
    'Vratislav',
    'Alfréd',
    'Valéria',
    'Alojz',
    'Paulína',
    'Sidónia',
    'Ján',
    'Tadeáš, Olívia',
    'Adriána',
    'Ladislav, Ladislava',
    'Beáta',
    'Peter, Pavol, Petra',
    'Melánia',
    'Diana',
    'Berta',
    'Miloslav',
    'Prokop',
    'Cyril, Metod',
    'Patrik, Patrícia',
    'Oliver',
    'Ivan',
    'Lujza',
    'Amália',
    'Milota',
    'Nina',
    'Margita',
    'Kamil',
    'Henrich',
    'Drahomír, Karmela, Rút',
    'Bohuslav',
    'Kamila',
    'Dušana',
    'Eliáš, Iľja',
    'Daniel',
    'Magdaléna',
    'Oľga',
    'Vladimír',
    'Jakub, Timur',
    'Anna, Hana, Anita',
    'Božena',
    'Krištof',
    'Marta',
    'Libuša',
    'Ignác',
    'Božidara',
    'Gustáv',
    'Jerguš',
    'Dominik, Dominika',
    'Hortenzia',
    'Jozefína',
    'Štefánia',
    'Oskar',
    'Ľubomíra',
    'Vavrinec',
    'Zuzana',
    'Darina',
    'Ľubomír',
    'Mojmír',
    'Marcela',
    'Leonard',
    'Milica',
    'Elena, Helena',
    'Lýdia',
    'Anabela, Liliana',
    'Jana',
    'Tichomír',
    'Filip',
    'Bartolomej',
    'Ľudovít',
    'Samuel',
    'Silvia',
    'Augustín',
    'Nikola, Nikolaj',
    'Ružena',
    'Nora',
    'Drahoslava',
    'Linda, Rebeka',
    'Belo',
    'Rozália',
    'Regína',
    'Alica',
    'Marianna',
    'Miriama',
    'Martina',
    'Oleg',
    'Bystrík',
    'Mária, Marlena',
    'Ctibor',
    'Ľudomil',
    'Jolana',
    'Ľudmila',
    'Olympia',
    'Eugénia',
    'Konštantín',
    'Ľuboslav, Ľuboslava',
    'Matúš',
    'Móric',
    'Zdenka',
    'Ľubor, Ľuboš',
    'Vladislav, Vladislava',
    'Edita',
    'Cyprián, Damián',
    'Václav',
    'Michal, Michaela',
    'Jarolím',
    'Arnold',
    'Levoslav',
    'Stela',
    'František',
    'Viera',
    'Natália',
    'Eliška',
    'Brigita',
    'Dionýz',
    'Slavomíra',
    'Valentína',
    'Maximilián',
    'Koloman',
    'Boris',
    'Terézia',
    'Vladimíra',
    'Hedviga',
    'Lukáš',
    'Kristián',
    'Vendelín',
    'Uršuľa',
    'Sergej',
    'Alojzia',
    'Kvetoslava',
    'Aurel',
    'Demeter',
    'Sabína',
    'Dobromila',
    'Klára',
    'Šimon, Simona',
    'Aurélia',
    'Denis, Denisa',
    '',
    'Hubert',
    'Karol',
    'Imrich',
    'Renáta',
    'René',
    'Bohumír',
    'Teodor',
    'Tibor',
    'Maroš, Martin',
    'Svätopluk',
    'Stanislav',
    'Irma',
    'Leopold',
    'Agnesa',
    'Klaudia',
    'Eugen',
    'Alžbeta',
    'Félix',
    'Elvíra',
    'Cecília',
    'Klement',
    'Emília',
    'Katarína',
    'Kornel',
    'Milan',
    'Henrieta',
    'Vratko',
    'Andrej, Ondrej',
    'Edmund',
    'Bibiána',
    'Oldrich',
    'Barbora, Barbara',
    'Oto',
    'Mikuláš',
    'Ambróz',
    'Marína',
    'Izabela',
    'Radúz',
    'Hilda',
    'Otília',
    'Lucia',
    'Branislava, Bronislava',
    'Ivica',
    'Albína',
    'Kornélia',
    'Sláva',
    'Judita',
    'Dagmara',
    'Bohdan',
    'Adela',
    'Nadežda, Naďa',
    'Adam, Eva',
    '',
    'Štefan',
    'Filoména',
    'Ivana, Ivona',
    'Milada',
    'Dávid',
    'Silvester'
  ]
  if (pocetDni === 365) {
    return meninyList.filter((x) => x !== 'Radomír')
  } else pocetDni === 366
  {
    return meninyList
  }
}
